### ISSUE TITLE
publishing templates

### ISSUE THREAD

**Issue by arieljake-bluescape** [4integration/3scale-cms#1]
Your code in the api only appears to create a template as a draft. Do you know what the api call is to publish a template? Or, alternatively, to create a template and specify the published version at the beginning? 

Thanks.

**Comment by 4integration** [comment]
Hi,
Since I do not maintain this code - just Github for publishing. I actually don't know.

**Comment by arieljake-bluescape** [comment]
Thanks for letting me know.
